# Generated by Django 5.0.2 on 2025-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
