# Generated by Django 5.0.2 on 2025-05-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0003_remove_invoice_updated_at_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="round_off",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
